SELECT
    CAST ("productType" AS INTEGER),
    asin,
    author,
    CAST ("availabilityAmazon" AS INTEGER),
    binding,
    "categoryTree_0",
    "categoryTree_1",
    "categoryTree_2",
    "categoryTree_3",
    "categoryTree_4",
    ean,
    CAST("hasReviews" AS INTEGER),
    CAST("isEligibleForSuperSaverShipping" AS INTEGER),
    CAST("isEligibleForTradeIn" AS INTEGER),
    CAST("isRedirectASIN" AS INTEGER),
    CAST("isSNS" AS INTEGER),
    languages_0,
    (CAST("lastPriceChange" AS INTEGER)+2156400)*60 AS "lastPriceChangeEpoch",
    (CAST("lastRatingUpdate" AS INTEGER)+2156400)*60 AS "lastRatingUpdateEpoch",
    (CAST("lastUpdate" AS INTEGER)+2156400)*60 AS "lastUpdateEpoch",
    CAST("newPriceIsMAP" AS INTEGER),
    CAST("numberOfItems" AS INTEGER),
    CAST("numberOfPages" AS INTEGER),
    CAST("packageHeight" AS INTEGER),
    CAST("packageLength" AS INTEGER),
    CAST("packageQuantity" AS INTEGER),
    CAST("packageWeight" AS INTEGER),
    CAST("packageWidth" AS INTEGER),
    "productGroup",
    "publicationDate",
    publisher,
    "releaseDate",
    CAST("rootCategory" AS BIGINT),
    CAST("stats_atIntervalStart" AS INTEGER),
    CAST(stats_avg AS INTEGER),
    CAST(stats_avg30 AS INTEGER),
    CAST(stats_avg90 AS INTEGER),
    CAST(stats_avg180 AS INTEGER),
    CAST(stats_current AS INTEGER),
    CAST("stats_outOfStockPercentage30" AS INTEGER),
    CAST("stats_outOfStockPercentage90" AS INTEGER),
    CAST("stats_outOfStockPercentageInInterval" AS INTEGER),
    title,
    (CAST("trackingSince" AS INTEGER)+2156400)*60 AS "trackingSinceEpoch",
    "type",
    upc,
    CAST(amazon_price AS INTEGER),
    CAST(marketplace_new_price AS INTEGER),
    CAST(marketplace_used_price AS INTEGER),
    CAST(sales_rank AS INTEGER),
	CAST(COALESCE(NULLIF(amazon_price,'-1'),NULLIF("marketplace_new_price",'-1'),NULLIF("marketplace_used_price",'-1')) AS INTEGER) AS price
	FROM public.keepa